// Generated by gencpp from file scout_service/POIVector.msg
// DO NOT EDIT!


#ifndef SCOUT_SERVICE_MESSAGE_POIVECTOR_H
#define SCOUT_SERVICE_MESSAGE_POIVECTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scout_service
{
template <class ContainerAllocator>
struct POIVector_
{
  typedef POIVector_<ContainerAllocator> Type;

  POIVector_()
    : num_pois(0)
    , x()
    , y()  {
    }
  POIVector_(const ContainerAllocator& _alloc)
    : num_pois(0)
    , x(_alloc)
    , y(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _num_pois_type;
  _num_pois_type num_pois;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _x_type;
  _x_type x;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::scout_service::POIVector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scout_service::POIVector_<ContainerAllocator> const> ConstPtr;

}; // struct POIVector_

typedef ::scout_service::POIVector_<std::allocator<void> > POIVector;

typedef boost::shared_ptr< ::scout_service::POIVector > POIVectorPtr;
typedef boost::shared_ptr< ::scout_service::POIVector const> POIVectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scout_service::POIVector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scout_service::POIVector_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace scout_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'scout_service': ['/home/shawk/catkin_ws/src/scout_service/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::scout_service::POIVector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scout_service::POIVector_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scout_service::POIVector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scout_service::POIVector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scout_service::POIVector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scout_service::POIVector_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scout_service::POIVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe25964ddf5f054dba5af44ea878d08b";
  }

  static const char* value(const ::scout_service::POIVector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe25964ddf5f054dULL;
  static const uint64_t static_value2 = 0xba5af44ea878d08bULL;
};

template<class ContainerAllocator>
struct DataType< ::scout_service::POIVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scout_service/POIVector";
  }

  static const char* value(const ::scout_service::POIVector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scout_service::POIVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8        num_pois\n\
float64[]   x\n\
float64[]   y\n\
";
  }

  static const char* value(const ::scout_service::POIVector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scout_service::POIVector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_pois);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct POIVector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scout_service::POIVector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scout_service::POIVector_<ContainerAllocator>& v)
  {
    s << indent << "num_pois: ";
    Printer<int8_t>::stream(s, indent + "  ", v.num_pois);
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.y[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCOUT_SERVICE_MESSAGE_POIVECTOR_H
