// Generated by gencpp from file scout_service/RoverState.msg
// DO NOT EDIT!


#ifndef SCOUT_SERVICE_MESSAGE_ROVERSTATE_H
#define SCOUT_SERVICE_MESSAGE_ROVERSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scout_service
{
template <class ContainerAllocator>
struct RoverState_
{
  typedef RoverState_<ContainerAllocator> Type;

  RoverState_()
    : rover_name()
    , data()  {
    }
  RoverState_(const ContainerAllocator& _alloc)
    : rover_name(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _rover_name_type;
  _rover_name_type rover_name;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::scout_service::RoverState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scout_service::RoverState_<ContainerAllocator> const> ConstPtr;

}; // struct RoverState_

typedef ::scout_service::RoverState_<std::allocator<void> > RoverState;

typedef boost::shared_ptr< ::scout_service::RoverState > RoverStatePtr;
typedef boost::shared_ptr< ::scout_service::RoverState const> RoverStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scout_service::RoverState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scout_service::RoverState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace scout_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'scout_service': ['/home/shawk/catkin_ws/src/scout_service/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::scout_service::RoverState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scout_service::RoverState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scout_service::RoverState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scout_service::RoverState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scout_service::RoverState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scout_service::RoverState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scout_service::RoverState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ee648f8131d2dc132d1a7f533af871f";
  }

  static const char* value(const ::scout_service::RoverState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ee648f8131d2dc1ULL;
  static const uint64_t static_value2 = 0x32d1a7f533af871fULL;
};

template<class ContainerAllocator>
struct DataType< ::scout_service::RoverState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scout_service/RoverState";
  }

  static const char* value(const ::scout_service::RoverState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scout_service::RoverState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string      rover_name\n\
float64[]   data\n\
";
  }

  static const char* value(const ::scout_service::RoverState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scout_service::RoverState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rover_name);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoverState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scout_service::RoverState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scout_service::RoverState_<ContainerAllocator>& v)
  {
    s << indent << "rover_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.rover_name);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCOUT_SERVICE_MESSAGE_ROVERSTATE_H
