// Generated by gencpp from file scout_service/RoverPosition.msg
// DO NOT EDIT!


#ifndef SCOUT_SERVICE_MESSAGE_ROVERPOSITION_H
#define SCOUT_SERVICE_MESSAGE_ROVERPOSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace scout_service
{
template <class ContainerAllocator>
struct RoverPosition_
{
  typedef RoverPosition_<ContainerAllocator> Type;

  RoverPosition_()
    : header()
    , rover_name()
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  RoverPosition_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , rover_name(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _rover_name_type;
  _rover_name_type rover_name;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;




  typedef boost::shared_ptr< ::scout_service::RoverPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scout_service::RoverPosition_<ContainerAllocator> const> ConstPtr;

}; // struct RoverPosition_

typedef ::scout_service::RoverPosition_<std::allocator<void> > RoverPosition;

typedef boost::shared_ptr< ::scout_service::RoverPosition > RoverPositionPtr;
typedef boost::shared_ptr< ::scout_service::RoverPosition const> RoverPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scout_service::RoverPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scout_service::RoverPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace scout_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'scout_service': ['/home/shawk/catkin_ws/src/scout_service/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::scout_service::RoverPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scout_service::RoverPosition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scout_service::RoverPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scout_service::RoverPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scout_service::RoverPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scout_service::RoverPosition_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scout_service::RoverPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de1caca4779cb70d04d3cdea86bec142";
  }

  static const char* value(const ::scout_service::RoverPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde1caca4779cb70dULL;
  static const uint64_t static_value2 = 0x04d3cdea86bec142ULL;
};

template<class ContainerAllocator>
struct DataType< ::scout_service::RoverPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scout_service/RoverPosition";
  }

  static const char* value(const ::scout_service::RoverPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scout_service::RoverPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header      header\n\
string      rover_name\n\
float64     x\n\
float64     y\n\
float64     z\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::scout_service::RoverPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scout_service::RoverPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.rover_name);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoverPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scout_service::RoverPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scout_service::RoverPosition_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rover_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.rover_name);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCOUT_SERVICE_MESSAGE_ROVERPOSITION_H
