// Generated by gencpp from file scout_service/RoverList.msg
// DO NOT EDIT!


#ifndef SCOUT_SERVICE_MESSAGE_ROVERLIST_H
#define SCOUT_SERVICE_MESSAGE_ROVERLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scout_service
{
template <class ContainerAllocator>
struct RoverList_
{
  typedef RoverList_<ContainerAllocator> Type;

  RoverList_()
    : rover_type()
    , rover_names()
    , x()
    , y()  {
    }
  RoverList_(const ContainerAllocator& _alloc)
    : rover_type(_alloc)
    , rover_names(_alloc)
    , x(_alloc)
    , y(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _rover_type_type;
  _rover_type_type rover_type;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _rover_names_type;
  _rover_names_type rover_names;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _x_type;
  _x_type x;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::scout_service::RoverList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scout_service::RoverList_<ContainerAllocator> const> ConstPtr;

}; // struct RoverList_

typedef ::scout_service::RoverList_<std::allocator<void> > RoverList;

typedef boost::shared_ptr< ::scout_service::RoverList > RoverListPtr;
typedef boost::shared_ptr< ::scout_service::RoverList const> RoverListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scout_service::RoverList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scout_service::RoverList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace scout_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'scout_service': ['/home/shawk/catkin_ws/src/scout_service/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::scout_service::RoverList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scout_service::RoverList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scout_service::RoverList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scout_service::RoverList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scout_service::RoverList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scout_service::RoverList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scout_service::RoverList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "759ccd0e1a51f7ac894526adf7ce14cd";
  }

  static const char* value(const ::scout_service::RoverList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x759ccd0e1a51f7acULL;
  static const uint64_t static_value2 = 0x894526adf7ce14cdULL;
};

template<class ContainerAllocator>
struct DataType< ::scout_service::RoverList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scout_service/RoverList";
  }

  static const char* value(const ::scout_service::RoverList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scout_service::RoverList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string      rover_type\n\
string[]    rover_names\n\
float64[]   x\n\
float64[]   y\n\
";
  }

  static const char* value(const ::scout_service::RoverList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scout_service::RoverList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rover_type);
      stream.next(m.rover_names);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoverList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scout_service::RoverList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scout_service::RoverList_<ContainerAllocator>& v)
  {
    s << indent << "rover_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.rover_type);
    s << indent << "rover_names[]" << std::endl;
    for (size_t i = 0; i < v.rover_names.size(); ++i)
    {
      s << indent << "  rover_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.rover_names[i]);
    }
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.y[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCOUT_SERVICE_MESSAGE_ROVERLIST_H
